config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :journey_acquisitions, only: [] do
    collection do
      get :checkout_session_redirect
    end
  end
  resources :journeys, only: %i[index new show create destroy] do
    resources :journey_stops, only: %i[new create destroy]
  end
  resources :pelicans,             only: %i[index show edit update], param: :username
  resources :relationships,        only: %i[create destroy]
  resources :payments,             only: [] do
    collection do
      post :create_checkout_session
    end
  end
  resources :watch_journeys, only: [:show], param: :access_code
  resources :map_pins,       only: [:index, :create, :destroy]

  resources :company, only: [] do
    collection do
      get :about_us
      get :how_it_works
    end
  end

  root 'journeys#index'
end

app/controllers/company_controller.rb
# frozen_string_literal: true

# CompanyController
class CompanyController < ApplicationController
  def about_us; end

  def how_it_works; end
end

app/helpers/company_helper.rb
# frozen_string_literal: true

# Methods used by views in companies
module CompanyHelper
  def company_title
    return 'MPelicans - How It Works' if params[:action] == 'how_it_works'
    return 'MPelicans - About Us'     if params[:action] == 'about_us'

    'MPelicans - Ideas for your next journey'
  end
end

app/views/company/about_us.html.erb
<meta name="description" content="
  My name is Valentin Lazar and I created this web application as a solution to my problem.
  I like to travel, but making an itinerary takes way too long. At least for me. I have to read countless
  articles by bloggers I do not know, save them if I like them, and later double-check what I
  saved. If I do not know the bloggers, the chance that we have the same taste is minimal.
  Do we like the same food? Do we enjoy the same attractions? And so on. The answer to all these
  is: probably not.
  The second option would be to check other social networks. The problem that I have here is that very little
  is about traveling.
  So the obvious solution for me was a platform only for traveling. It should be simple and easy to
  use. I want to see some pictures from my friends and save the location. Thats it. No ads,
  no countless posts about 10 million different things. Just traveling.
  I hope you enjoy it,
  Valentin Lazar
">

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="row">
      <div class="col-12">
        <div class="mb-3">
          <h1 class="h3 d-inline align-middle">About Us</h1>
        </div>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <p>
              Hi,
            </p>
            <p>
              My name is Valentin Lazar and I created this web application as a solution to my problem.
              I like to travel, but making an itinerary takes way too long. At least for me. I have to read countless
              articles by bloggers I do not know, save them if I like them, and later double-check what I
              saved. If I do not know the bloggers, the chance that we have the same taste is minimal.
              Do we like the same food? Do we enjoy the same attractions? And so on. The answer to all these
              is: probably not.
            </p>
            <p>
              The second option would be to check other social networks. The problem that I have here is that very little
              is about traveling.
            </p>
            <p>
              So the obvious solution for me was a platform only for traveling. It should be simple and easy to
              use. I want to see some pictures from my friends and save the location. Thats it. No ads,
              no countless posts about 10 million different things. Just traveling.
            </p>
            <p>
              I hope you enjoy it,
              <br>
              Valentin Lazar
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/company/how_it_works.html.erb
<meta name="description" content="
  Share a memory
  If you want to share a memory, firstly, you have to create a journey. 
  After a journey is made, you can add multiple stops to it. For example, you are going to Italy tomorrow. 
  It's a perfect time to create a journey. The title could be 'Excited to visit Italy for my first time.' 
  In the description, you can add a few ideas from your plans, and remember to add some pictures.
  After you create a journey, you can add multiple stops to it. For example,
  after arriving in Italy, you find a great pizzeria. Create a stop for it. 
  Add a title, description, and a few pictures. A new detail, a very important one, is the location. 
  The location is essential because other travelers can save it to their map and visit it later.
  Remember to add a stop to your journey each time you see something, visit something, or see fantastic scenery.
  Find new ideas travel ideas
  The idea of the application is to find new, unique places to visit and save them. If browsing through the journeys and seeing a superb stop, 
  you can go to the journey stop page and save the location by pressing "Save Location." After you save the pin, you can view it on the Pins page.
">

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="row">
      <div class="col-12">
        <div class="mb-3">
          <h1 class="h3 d-inline align-middle">How It Works</h1>
        </div>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h3>
              Share a memory
            </h3>
            <p>
              If you want to share a memory, firstly, you have to <a href="<%= new_journey_url %>">create a journey</a>. 
              After a journey is made, you can add multiple stops to it. For example, you are going to Italy tomorrow. 
              It's a perfect time to create a journey. The title could be 'Excited to visit Italy for my first time.' 
              In the description, you can add a few ideas from your plans, and remember to add some pictures.
            </p>
            <p>
              After you create a journey, you can add multiple stops to it. For example,
              after arriving in Italy, you find a great pizzeria. Create a stop for it. 
              Add a title, description, and a few pictures. A new detail, a very important one, is the location. 
              The location is essential because other travelers can save it to their map and visit it later.
            </p>
            <p>
              Remember to add a stop to your journey each time you see something, visit something, or see fantastic scenery.
            </p>
            <h3>
              Find new travel ideas
            </h3>
            <p>
              The idea of the application is to find new, unique places to visit and save them. When browsing through the journeys you see a superb stop, 
              you can go to the journey stop page and save the location by pressing "Save Location." After you save the pin, you can view it on the <a href="<%= map_pins_url %>">Pins page</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>