config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :journey_acquisitions, only: [] do
    collection do
      get :checkout_session_redirect
    end
  end
  resources :journeys, only: %i[index new show create destroy] do
    resources :journey_stops, only: %i[new create destroy]
  end
  resources :pelicans,             only: %i[index show edit update], param: :username
  resources :relationships,        only: %i[create destroy]
  resources :payments,             only: [] do
    collection do
      post :create_checkout_session
    end
  end
  resources :watch_journeys, only: [:show], param: :access_code
  resources :map_pins,       only: [:index, :create, :destroy]

  resources :company, only: [] do
    collection do
      get :about_us
      get :how_it_works
    end
  end

  root 'journeys#index'
end

app/controllers/pelicans_controller.rb
# frozen_string_literal: true

# User controller
class PelicansController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  before_action :set_user, only: %i[edit update]

  def index
    @users = Retrievers::User.new(query_string: params.dig(:pelicans, :query_string)).fetch
    @users = @users.page params[:page]
  end

  def show
    @user = User.find_by!(username: params[:username])

    @journeys = if current_user_on_his_profile_page?
                  current_users_journeys
                else
                  another_users_journeys
                end
  end

  def edit; end

  def update
    @user.update(update_params)

    reset_password if can_reset_password?

    if @user.errors.blank?
      render_success_message(message: 'Your user was updated')
    else
      render_alert_message
    end

    render 'edit'
  end

  private

  def current_user_on_his_profile_page?
    current_user == @user
  end

  def current_users_journeys
    Retrievers::Journey.new(user: current_user, which_journeys: 'mine').fetch
  end

  def another_users_journeys
    Retrievers::Journey.new(user: @user, which_journeys: 'users').fetch
  end

  def set_user
    @user = current_user
  end

  def reset_password
    current_user.reset_password(
      password,
      password_confirmation
    )

    bypass_sign_in current_user
  end

  def update_params
    params.require(:user).permit(
      :biography,
      :image,
      :username
    )
  end

  def can_reset_password?
    password && password_confirmation
  end

  def password
    params[:user][:password]
  end

  def password_confirmation
    params[:user][:password_confirmation]
  end
end

app/helpers/pelicans_helper.rb
# frozen_string_literal: true

# Methods used by views in pelicans
module PelicansHelper
  # rubocop:disable Rails/HelperInstanceVariable
  def pelicans_title
    return "MPelicans - #{@user.username}" if @user

    'MPelicans - Ideas for your next journey'
  end
  # rubocop:enable Rails/HelperInstanceVariable

  def journeys_page_title
    params[:which_journeys].camelize
  end
end

app/views/pelicans/_follow_unfollow.html.erb
<% if follower %>
  <% if can?(:create, Relationship.new, follower, followee) %>
    <%= link_to 'Follow', relationships_path(followee_id: followee.id), method: :post, class: 'btn btn-sm btn-primary pelican-path' %>
  <% end %>

  <% relationship =  Relationship.find_by(follower_id: follower.id, followee_id: followee.id) %>
  <% if can?(:destroy, relationship, follower, followee) %>
    <%= link_to 'Unfollow', relationship_path(id: relationship.id), method: :delete, class: 'btn btn-sm btn-danger pelican-path' %>
  <% end %>
<% else %>
  <%= link_to 'Follow', new_user_session_path, class: 'btn btn-sm btn-primary pelican-path' %>
<% end %>

app/views/pelicans/_pelican.html.erb
<div class="card md-3">
  <div class="card-header text-center">
    <%= render partial: 'pelicans/profile_image_big', locals: { user: user } %>
    <h5 class="card-title mb-0">
      <%= link_to user.username, pelican_path(user.username), class: 'pelican-path pelican-name card-link' %>
    </h5>
    <div class="text-muted mb-2"><%= user.biography %></div>
    <ul class="list-unstyled mb-0">
      <li class="mb-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map align-middle me-2"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"></polygon><line x1="8" y1="2" x2="8" y2="18"></line><line x1="16" y1="6" x2="16" y2="22"></line></svg>
        Journeys: <%= number_to_human(user.journeys.count) %>
      </li>
      <li class="mb-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user align-middle me-2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
        Followers: <%= number_to_human(user.followers.count) %>
      </li>
    </ul>
  </div>

  <div class="card-body text-center">
    <%= render partial: 'pelicans/follow_unfollow', locals: { follower: current_user, followee: user } %>
  </div>
</div>

app/views/pelicans/_profile_image.html.erb
<% if user.image.attached? %>
  <img src="<%= url_for(user.image.variant(:max)) %>" class="rounded-circle me-1" alt="Avatar" width="28", height="28">        
<% else %>
  <%= image_tag "avatars/avatar.png", class: "rounded-circle me-1", alt: "Avatar", width: "28", height: "28" %>
<% end %>

app/views/pelicans/_profile_image_big.html.erb
<% if user.image.attached? %>
  <img src="<%= url_for(user.image.variant(:max)) %>" class="img-fluid rounded-circle mb-2" width='128' height='128'>
<% else %>
  <%= image_tag "avatars/avatar.png", class: "img-fluid rounded-circle mb-2", width: '128', height: '128' %>
<% end %>

app/views/pelicans/edit.html.erb
<div class="mb-3">
  <h1 class="h3 d-inline align-middle">Profile</h1>
</div>

<div class="row">
  <div class="col-md-3 col-xl-2">
    <div class="card">
    	<div class="card-header">
    		<h5 class="card-title">Profile Settings</h5>
    	</div>

    	<div class="list-group list-group-flush" role="tablist">
    		<a class="list-group-item list-group-item-action active" data-bs-toggle="list" href="#account" role="tab" aria-selected="true">
    			Account
    		</a>
    		<a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#password" role="tab" aria-selected="false" tabindex="-1">
    			Password
    		</a>
    	</div>
    </div>
  </div>

  <div class="col-md-9 col-xl-10">
  	<div class="tab-content">
  		<div class="tab-pane fade show active" id="account" role="tabpanel">
  			<div class="card">
  				<div class="card-header">
  					<h5 class="card-title">Public info</h5>
  				</div>
  				<div class="card-body">
            <%= form_for @user, url: pelican_path(@user.username) do |f| %>
              <div class="mb-3" style="color: red;">
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </div>
              <div class="row">
                <div class="col-md-8">
                  <div class="mb-3">
                    <%= f.label :username, class: 'form-label' %>
                    <em>(can contain letters and numbers only)</em>
                    <br/>
                    <%= f.text_field :username, required: true, autofocus: true, autocomplete: "username", value: current_user.username, class: 'form-control' %>
                  </div>
                  <div class="mb-3">
                    <%= f.label :biography, class: 'form-label' %><br />
                    <%= f.text_area :biography, value: @user.biography, class: 'form-control' %>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="text-center">
                    <%= render partial: 'pelicans/profile_image_big', locals: { user: @user } %>
                    <div class="mt-2">
                      <%= f.file_field :image, accept: ACCEPTED_CONTENT_TYPE %>
                    </div>
                  </div>
                </div>
              </div>
              <%= f.submit "Save changes", class: "btn btn-primary" %>
            <% end %>
  				</div>
  			</div>
  		</div>

  		<div class="tab-pane fade" id="password" role="tabpanel">
  			<div class="card">
          <div class="card-header">
  					<h5 class="card-title">Password</h5>
  				</div>
  				<div class="card-body">
  					<%= form_for @user, url: pelican_path(@user.username) do |f| %>
  						<div class="mb-3">
  							<%= f.label :password, class: 'form-label' %><br />
                <%= f.password_field :password, required: true, class: 'form-control' %>
  						</div>
  						<div class="mb-3">
  							<%= f.label :password_confirmation, class: 'form-label' %><br />
  							<%= f.password_field :password_confirmation, required: true, class: 'form-control' %>
  						</div>
    					<%= f.submit "Save password", class: "btn btn-primary" %>
  					<% end %>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
</div>

app/views/pelicans/index.html.erb
<div class="mb-3">
  <h1 class="h3 d-inline align-middle">Pelicans</h1>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
    	<div class="card-body">
    		<div class="row">
    			<div class="w-100"></div>
    			<div class="col-md">
    				<div class="mb-0">
              <%= form_for :pelicans, html: { method: :get } do |f| %>
                <div class="input-group">
                  <%= f.text_field :query_string, required: true, class: 'form-control', placeholder: 'Search...' %>
                  <%= f.submit 'Search', class: 'btn btn-primary' %>
                </div>
              <% end %>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
  </div>
</div>

<div class="row">
	<% if @users.empty? %>
    <div class="mb-3">
      <h1 class="h4 d-inline align-middle">No pelicans found ...</h1>
    </div>
	<% else %>
		<% @users.each do |user| %>
      <div class="col-md-4 col-xl-3">
        <%= render partial: 'pelicans/pelican', locals: { user: user } %>
      </div>
		<% end %>
	<% end %>
</div>

<div class="mb-3 float-end">
  <%= paginate @users, theme: 'bootstrap4' %>
</div>

app/views/pelicans/show.html.erb
<div class="row">
  <div class="col-12 col-md-4 col-lg-3">
    <%= render partial: 'pelicans/pelican', locals: { user: @user } %>
  </div>
  <div class="col-12 col-md-8 col-lg-6">
    <%= render partial: 'journeys/journeys', locals: { journeys: @journeys } %>
  </div>
</div>