config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :journey_acquisitions, only: [] do
    collection do
      get :checkout_session_redirect
    end
  end
  resources :journeys, only: %i[index new show create destroy] do
    resources :journey_stops, only: %i[new create destroy]
  end
  resources :pelicans,             only: %i[index show edit update], param: :username
  resources :relationships,        only: %i[create destroy]
  resources :payments,             only: [] do
    collection do
      post :create_checkout_session
    end
  end
  resources :watch_journeys, only: [:show], param: :access_code
  resources :map_pins,       only: [:index, :create, :destroy]

  resources :company, only: [] do
    collection do
      get :about_us
      get :how_it_works
    end
  end

  root 'journeys#index'
end

app/models/journey.rb
# frozen_string_literal: true

# Journey Model
class Journey < ApplicationRecord
  include Rails.application.routes.url_helpers
  include JourneyImagesConcern
  include Imageable

  MAXIMUM_NUMBER_OF_IMAGES = 5
  AVAILABLE_FILTER_BUTTONS = %w[latest mine bought].freeze

  paginates_per 10

  belongs_to :user
  has_many :journey_stops, dependent: :destroy
  has_many :paid_journeys, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :paying_users, through: :paid_journeys, source: :user
  has_many :uploaded_images, as: :imageable, dependent: :destroy

  has_rich_text :description

  validates :access_code,
            :latest_journey_stop_added_at,
            :title,
            presence: true

  validate :images_are_present
  validate :maximum_number_of_images

  default_scope { order(latest_journey_stop_added_at: :desc) }

  alias_attribute :plus_code, :start_plus_code

  enum :access_type, {
    public_journey: 0,
    protected_journey: 1,
    private_journey: 2,
    monetized_journey: 3
  }

  before_validation :add_access_code
  before_validation :set_latest_journey_stop_added_at

  def meta_description_content
    [
      title,
      description.to_plain_text,
      journey_stops.map(&:meta_description_content)
    ]
      .flatten
      .join(' ')
  end

  def pins
    journey_stops.map { |pinnable| Pin.new(pinnable:).to_pin }
  end

  def lastest_journey_stop_id
    journey_stops
      .unscoped
      .order(created_at: :asc)
      .last
      .id
  end

  def simple_class_name
    'Journey'
  end

  def modal_id
    "journey-#{id}"
  end

  def map_id
    "map-#{modal_id}"
  end

  def link_to_self
    journey_url(self, host: ENV.fetch('DEFAULT_HOST'))
  end

  private

  def set_latest_journey_stop_added_at
    return if latest_journey_stop_added_at

    self.latest_journey_stop_added_at = DateTime.now
  end

  def add_access_code
    return if access_code

    self.access_code = SecureRandom.uuid
  end

  def maximum_number_of_images
    return if passed_images_count <= MAXIMUM_NUMBER_OF_IMAGES

    errors.add :images, :invalid, message: "can't post more than #{MAXIMUM_NUMBER_OF_IMAGES}"
  end
end

app/controllers/journeys_controller.rb
# frozen_string_literal: true

# CRUD For Journey
class JourneysController < ApplicationController
  include PermittedParameters

  before_action :authenticate_user!, except: %i[index show]

  PERMITTED_PARAMETERS = %i[
    accepts_recommendations
    access_type
    description
    title
  ].freeze

  def index
    redirect_to journeys_path and return unless params[:which_journeys].blank? || valid_filter?

    @journeys = Retrievers::Journey.new(user: current_user, which_journeys: params[:which_journeys]).fetch
    @journeys = @journeys.page params[:page]
  end

  def show
    @journey = Journey.find(params[:id])

    authorize_journey(:show)

    increase_views_count
  end

  def new
    @journey = Journey.new
  end

  def create
    @journey = new_journey

    authorize_journey(:create)

    if @journey.save
      post_create_actions

      success_message(message: 'Your journey was created.')

      redirect_to journey_path(@journey)
    else
      render_alert_message

      render action: 'new'
    end
  end

  def destroy
    @journey = Journey.find(params[:id])

    authorize_journey(:destroy)

    if @journey.destroy
      success_message(message: 'Your journey was deleted.')

      redirect_to root_path
    else
      render_alert_message

      redirect_to journey_path(@journey)
    end
  end

  private

  def valid_filter?
    Journey::AVAILABLE_FILTER_BUTTONS.include?(params[:which_journeys])
  end

  # rubocop:disable Rails/SkipsModelValidations
  def increase_views_count
    return if logged_in_user_created_journey?

    @journey.increment!(:views_count)
  end
  # rubocop:enable Rails/SkipsModelValidations

  def logged_in_user_created_journey?
    current_user == @journey.user
  end

  def new_journey
    Journey.new(permitted_parameters(
      model: :journey,
      permitted_parameters: PERMITTED_PARAMETERS
    ).merge(user_id: current_user.id))
  end

  def post_create_actions
    enqueue_process_images_job
    unlink_tempfiles
    notify_users
  end

  def enqueue_process_images_job
    ImagesProcessors::Validator.new(
      imageable_id: @journey.id,
      imageable_type: @journey.class.name,
      http_uploaded_files: params[:journey][:images]
    ).run
  end

  def unlink_tempfiles
    params[:journey][:images].each do |http_file|
      http_file.tempfile.unlink
    end
  end

  def notify_users
    NotifierJobs::NewJourney.perform_async(@journey.id, @journey.user_id)
  end

  def authorize_journey(method)
    authorize! method, @journey
  end
end

app/helpers/journeys_helper.rb
# frozen_string_literal: true

# Methods used by views in journeys
module JourneysHelper
  # rubocop:disable Rails/HelperInstanceVariable
  def journeys_title
    return "MPelicans - #{@journey.title}"    if params[:action] == 'show'
    return 'MPelicans - Create a new journey' if params[:action] == 'new'

    'MPelicans - Ideas for your next journey'
  end
  # rubocop:enable Rails/HelperInstanceVariable

  def journeys_page_title
    params[:which_journeys].camelize
  end
end

app/views/journeys/_buy_button.html.erb
<% if current_user.nil? || journey.user != current_user %>
  <% if can?(:buy, journey) %>
    <div class="row mb-3">
      <div class="col-12">
        <%= link_to create_checkout_session_payments_path(journey_id: journey.id), method: :post, class: 'btn btn-success float-end mt-n1' do %>
          <i class="align-middle" data-feather="lock"></i> <span class="align-middle">Buy</span>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/journeys/_journey.html.erb
<meta name="description" content="<%= @journey.meta_description_content %>">

<div class="row" data-controller="scrollable">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="row" data-controller="lightbox"> 
      <div class="col-12">
        <% if current_user && can?(:edit, @journey) %>
          <%= link_to '+ New Stop', new_journey_journey_stop_path(@journey), class: 'btn btn-primary  float-end mt-n1' %>
        <% end %>
      </div>
    <div>

    <div class="row">
      <div class="col-12">
        <div class="mb-3">
          <h1 class="d-inline-block" id="journey-title"><%= @journey.title %></h1>

          <%= render partial: 'shared/journey_journey_stop/map', locals: { journey_or_journey_stop: @journey } %>
          <%= render partial: 'shared/journey_journey_stop/share', locals: { journey: @journey } %>
        </div>

        <%= render partial: 'shared/journey_journey_stop/privacy',      locals: { journey: @journey }%>
      </div>
    </div>

    <%= render partial: 'shared/journey_journey_stop/creator',      locals: { user: @journey.user, journey: @journey }%>
    <%= render partial: 'shared/journey_journey_stop/description',  locals: { journey_or_journey_stop: @journey }%>
    <%= render partial: 'journeys/journey_journey_stops_cards',     locals: { journey: @journey }%>
    <%= render partial: 'shared/journey_journey_stop/destroy',      locals: { journey_or_journey_stop: @journey, path: journey_path(@journey) }%>
  </div>
</div>

app/views/journeys/_journey_card.html.erb
<div class="card">
  <div class="card-header">
    <div class="mb-3">
      <h1 class="d-inline-block">
        <%= journey.title %> 
      </h1>

      <%= render partial: 'shared/journey_journey_stop/map', locals: { journey_or_journey_stop: journey } %>
    </div>

    <%= render partial: 'shared/journey_journey_stop_card/creator', locals: { user: journey.user, journey: journey }%>
  </div>

  <div class="card-body">
    <%= render partial: 'shared/journey_journey_stop_card/images_grid', locals: { journey_or_journey_stop: journey } %>
  </div>

  <div class="card-header">
    <%= render partial: 'journeys/view_buttons', locals: { journey: journey } %>
    <%= render partial: 'journeys/buy_button',   locals: { journey: journey } %>
  </div>
</div>

app/views/journeys/_journey_journey_stops_cards.html.erb
<div class="row">
  <% unless journey.journey_stops.empty? %>
    <% journey.journey_stops.each_with_index do |journey_stop, index| %>
      <div class="col-12">
        <%= render partial: 'journey_stops/journey_stop_card', locals: { journey_stop: journey_stop, index: index } %>
      </div>
    <% end %>
  <% end %>

  <div class="col-12">
    <%= render partial: 'shared/journey_journey_stop/journey_images_card', locals: { journey: @journey } %>
  </div>
</div>

app/views/journeys/_journeys.html.erb
<div data-controller="lightbox">
	<% if journeys.empty? %>
    <h1 class="h4 d-inline align-middle">There are no journeys yet.</h1>
	<% else %>
		<% journeys.each do |journey| %>
      <%= render partial: 'journeys/journey_card', locals: { journey: journey } %>
		<% end %>
	<% end %>
</div>

app/views/journeys/_view_buttons.html.erb
<% if can?(:show, journey) %>
  <div class="row">
    <div class="col-12 p-1">
      <% if !Rails.env.test? && journey.pins.present? %>
        <a class="btn btn-secondary float-end mt-n1" data-bs-toggle="modal" data-bs-target="#<%= journey.modal_id %>">
          <i class="align-middle" data-feather="map-pin"></i> <span class="align-middle"></span>
          Open Map
        </a>

        <%= link_to 'View Journey', journey_path(journey), class: 'btn btn-primary float-end me-1 mt-n1' %>
      <% else %>
        <%= link_to 'View Journey', journey_path(journey), class: 'btn btn-primary float-end mt-n1' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/journeys/index.html.erb
<meta name="description" content="Ideas for your next journey.">

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <% if current_user %>
      <div class="row">
        <div class="col-12">
          <% Journey::AVAILABLE_FILTER_BUTTONS.each do |filter_button| %>
            <%= link_to filter_button.camelize, 
                        journeys_path(which_journeys: filter_button),
                        class: "btn #{which_journeys_button_class(which_journeys: filter_button)}"
            %>
          <% end %>

          <%= link_to "+ New Journey", new_journey_path, class: 'btn btn-primary float-end mt-n1' %>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <br>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-12">
        <%= render partial: 'journeys', locals: { journeys: @journeys } %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="mb-3 float-end">
          <%= paginate @journeys, theme: 'bootstrap4' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/journeys/new.html.erb
<meta name="description" content="Create A New Journey.">

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="row">
      <div class="col-12">
        <h1 class="h3 d-inline align-middle">Start a Journey</h1>
      </div>
    </div>

    <br>

    <div class="row" data-controller="documents">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= form_for @journey do |f| %>
              <div class="mb-3" style="color: red;">
                <% @journey.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </div>

              <div class="mb-3">
                <%= f.label :title, class: 'form-label' %>
                <%= f.text_field :title, required: true, class: 'form-control' %>
              </div>

              <div class="mb-3">
                <%= f.label :description, class: 'form-label' %>
                <%= f.rich_text_area :description, class: 'form-control' %>
              </div>

              <div class="mb-3">
                <label class="form-label">
                  Access Type
                </label>

                <div class="form-check">
                  <label>
                    <%= f.radio_button :access_type, 'public_journey', checked: true, class: 'form-check-input' %>
                    Public
                    <br>
                    <em>Anyone can see this journey.</em>
                  </label>
                </div>

                <div class="form-check">
                  <label>
                    <%= f.radio_button :access_type, 'protected_journey', class: 'form-check-input' %>
                    Protected
                    <br>
                    <em>We will generate a private link to share for this journey.</em>
                  </label>
                </div>

                <div class="form-check">
                  <label>
                    <%= f.radio_button :access_type, 'private_journey', class: 'form-check-input' %>
                    Private
                    <br>
                    <em>Only you can view this journey.</em>
                  </label>
                </div>

                <div class="form-check">
                  <label>
                    <%= f.radio_button :access_type, 'monetized_journey', class: 'form-check-input' %>
                    Monetized
                    <br>
                    <em>Users have to pay <b>$2.00</b> in order to see this journey.</em>
                    <br>
                    <em>After taxes you will receive <b>$1.25</b>.</em>
                  </label>
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label">
                  Add the first pictures of your journey
                  <br>
                  <strong>
                    Maximum <%= Journey::MAXIMUM_NUMBER_OF_IMAGES %> images.
                  </strong>
                </label>
                <br>
                <%= f.file_field :images, multiple: true, required: true, accept: ACCEPTED_CONTENT_TYPE %>
              </div>

              <div class="actions" data-controller="pleasewait" data-pleasewait-formid-value="new_journey" >
                <button class='btn btn-primary' id="form_submit_button" data-action="click->pleasewait#submitForm">Create</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/journeys/show.html.erb
<%= render 'journey' %>

<a data-bs-toggle="modal" data-bs-target="#<%= @journey.modal_id %>">
  <div class="settings-toggle">
    <i class="align-middle" data-feather="map-pin"></i><span class="align-middle"></span>
  </div>
</a>