config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :journey_acquisitions, only: [] do
    collection do
      get :checkout_session_redirect
    end
  end
  resources :journeys, only: %i[index new show create destroy] do
    resources :journey_stops, only: %i[new create destroy]
  end
  resources :pelicans,             only: %i[index show edit update], param: :username
  resources :relationships,        only: %i[create destroy]
  resources :payments,             only: [] do
    collection do
      post :create_checkout_session
    end
  end
  resources :watch_journeys, only: [:show], param: :access_code
  resources :map_pins,       only: [:index, :create, :destroy]

  resources :company, only: [] do
    collection do
      get :about_us
      get :how_it_works
    end
  end

  root 'journeys#index'
end

app/models/journey_stop.rb
# frozen_string_literal: true

# JourneyStop Model
class JourneyStop < ApplicationRecord
  include Rails.application.routes.url_helpers
  include Imageable

  MAXIMUM_NUMBER_OF_IMAGES = 5

  belongs_to :journey
  has_many :notifications, dependent: :destroy
  has_many :uploaded_images, as: :imageable, dependent: :destroy
  has_many :map_pins, dependent: :nullify
  has_rich_text :description

  validates :title, :lat, :long, presence: true
  validate :images_are_present
  validate :maximum_number_of_images

  delegate :user, to: :journey

  default_scope { order(created_at: :desc) }

  before_create :set_latest_journey_stop_added_at

  def meta_description_content
    [title, description.to_plain_text]
  end

  def pin
    Pin.new(pinnable: self).to_pin
  end

  def pins
    [pin]
  end

  def link_to_self
    journey_url(journey, scroll_to: anchor_id, host: ENV.fetch('DEFAULT_HOST'))
  end

  def all_mini_thumbnails
    images_urls(variant: :mini_thumbnail)
  end

  def all_thumbnails
    images_urls(variant: :thumbnail)
  end

  def all_mobiles
    images_urls(variant: :mobile)
  end

  def all_maxs
    images_urls(variant: :max)
  end

  def simple_class_name
    'Stop'
  end

  def anchor_id
    "journey-stop-id-#{id}"
  end

  def link_to_google_maps
    return journey_stop_place_url if place_id.present?

    journey_stop_coordinates_url
  end

  def belongs_to_a_place?
    place_id.present?
  end

  def journey_stop_place_url
    "https://www.google.com/maps/search/?api=1&query=Google&query_place_id=#{place_id}"
  end

  def journey_stop_coordinates_url
    "https://www.google.com/maps/search/?api=1&query=#{lat},#{long}"
  end

  private

  # rubocop:disable Rails/SkipsModelValidations
  def set_latest_journey_stop_added_at
    journey.update_attribute(:latest_journey_stop_added_at, DateTime.now)
  end
  # rubocop:enable Rails/SkipsModelValidations

  def maximum_number_of_images
    return if passed_images_count <= MAXIMUM_NUMBER_OF_IMAGES

    errors.add :images, :invalid, message: "can't post more than #{MAXIMUM_NUMBER_OF_IMAGES}"
  end
end

app/controllers/journey_stops_controller.rb
# frozen_string_literal: true

# CRUD For Journey Stop
class JourneyStopsController < ApplicationController
  include PermittedParameters

  PERMITTED_PARAMETERS = %i[
    description
    journey_id
    lat
    long
    title
    place_id
  ].freeze

  def new
    @journey_stop = JourneyStop.new(journey_id: params[:journey_id])
  end

  def create
    @journey_stop = new_journey_stop

    authorize_journey_stop(:create)

    if @journey_stop.save
      post_create_actions

      success_message(message: 'Your journey stop was created.')

      redirect_to journey_path(@journey_stop.journey)
    else
      render_alert_message

      render action: 'new'
    end
  end

  def destroy
    @journey_stop = JourneyStop.find(params[:id])

    authorize_journey_stop(:destroy)

    journey = @journey_stop.journey

    if @journey_stop.destroy
      success_message(message: 'Your journey stop was deleted.')
    else
      alert_message
    end

    redirect_to journey_path(journey)
  end

  private

  def new_journey_stop
    JourneyStop.new(
      permitted_parameters(
        model: :journey_stop,
        permitted_parameters: PERMITTED_PARAMETERS
      )
    )
  end

  # rubocop:disable Rails/SkipsModelValidations
  def increase_views_count
    return if logged_in_user_created_journey?

    @journey_stop.increment!(:views_count)
  end
  # rubocop:enable Rails/SkipsModelValidations

  def logged_in_user_created_journey?
    current_user == @journey_stop.user
  end

  def post_create_actions
    enqueue_process_images_job
    unlink_tempfiles
    notify_users
  end

  def authorize_journey_stop(method)
    authorize! method, @journey_stop
  end

  def enqueue_process_images_job
    ImagesProcessors::Validator.new(
      imageable_id: @journey_stop.id,
      imageable_type: @journey_stop.class.name,
      http_uploaded_files: params[:journey_stop][:images]
    ).run
  end

  def unlink_tempfiles
    params[:journey_stop][:images].each do |http_file|
      http_file.tempfile.unlink
    end
  end

  def notify_users
    journey = @journey_stop.journey

    NotifierJobs::NewJourneyStop.perform_async(journey.id, @journey_stop.id, journey.user_id)
  end
end

app/helpers/journey_stops_helper.rb
# frozen_string_literal: true

# Methods used by views in journeys
module JourneyStopsHelper
  def journey_stops_title
    'MPelicans - Create A New Journey Stop'
  end
end

app/views/journey_stops/_journey_stop_card.html.erb
<div class="card journey-stop-card" id="<%= journey_stop.anchor_id %>">
  <div class="card-header">
    <div class="mb-3">
      <h1 class="d-inline-block">
        <%= journey_stop.title %>
      </h1>

      <h6 class="card-subtitle text-muted">
        created <%= time_ago_in_words(journey_stop.created_at) %> ago
      </h6>
    </div>
  </div>

  <div class="card-body">
    <h4>
      <%= render partial: 'shared/journey_journey_stop/description', locals: { journey_or_journey_stop: journey_stop } %>
    </h4>

    <%= render partial: 'shared/journey_journey_stop_card/images_grid', locals: { journey_or_journey_stop: journey_stop } %>
  </div>

  <div class="card-header">
    <%= render partial: 'shared/journey_journey_stop/destroy', locals: { journey_or_journey_stop: journey_stop, path: journey_journey_stop_path(journey_stop.journey, journey_stop) } %>
    <%= render partial: 'map_pins/pin_unpin', locals: { current_user: current_user, journey_stop: journey_stop, id: dom_id(journey_stop, :save_pin) } %>
  </div>
</div>

app/views/journey_stops/new.html.erb
<meta name="description" content="Create A New Journey Stop.">

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="row">
      <div class="col-12">
        <div class="mb-3">
          <h1 class="h3 d-inline align-middle">Make a Stop</h1>
        </div>
      </div>
    </div>
      
    <div class="row" data-controller="documents">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= form_for [@journey_stop.journey, @journey_stop] do |f| %>
              <%= f.hidden_field :journey_id, value: params[:journey_id] %>
              <%= f.hidden_field :lat %>
              <%= f.hidden_field :long %>
              <%= f.hidden_field :place_id %>

              <div class="mb-3" style="color: red;">
                <% @journey_stop.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </div>

              <div class="mb-3">
                <%= f.label :title, class: 'form-label' %>
                <%= f.text_field :title, required: true, class: 'form-control' %>
              </div>

              <div class="mb-3">
                <%= f.label :description, class: 'form-label' %>
                <%= f.rich_text_area :description, class: 'form-control' %>
              </div>

              <%= 
                render partial: 'shared/location', 
                      locals: { 
                          message: 'What is your current stops location?', 
                          lat_element_id: '#journey_stop_lat', 
                          long_element_id: '#journey_stop_long',
                          place_id_element_id: '#journey_stop_place_id'
                        } 
              %>

              <div class="mb-3">
                <label class="form-label">
                  Add pictures from the stop you made
                  <br>
                  <strong>
                    Maximum <%= JourneyStop::MAXIMUM_NUMBER_OF_IMAGES %> images.
                  </strong>
                </label>
                <br>
                <%= f.file_field :images, multiple: true, required: true, accept: ACCEPTED_CONTENT_TYPE %>
              </div>

              <div class="actions">
                <div class="actions" data-controller="pleasewait" data-pleasewait-formid-value="new_journey_stop" >
                  <button disabled="disabled" class='btn btn-primary' id="form_submit_button" data-action="click->pleasewait#submitForm">Create</button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>